In [1]:
import torch
print(torch.__version__)

2.7.1+cu126


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [7]:
matrix = torch.tensor([[2,5],[5,8]])
matrix

tensor([[2, 5],
        [5, 8]])

In [9]:
print(matrix[0])
print(matrix.shape)

tensor([2, 5])
torch.Size([2, 2])


In [10]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor 

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 3, 3])


In [14]:
### Random Tensor
rand_tens = torch.rand(3,4)
rand_tens

tensor([[0.3245, 0.7574, 0.6837, 0.0039],
        [0.5642, 0.6985, 0.1788, 0.2568],
        [0.8193, 0.5371, 0.8204, 0.7286]])

Random tenor with similar shape or image tensor

In [19]:
rand_imagesize_tensor = torch.rand(size=(3,224,224))#hWClr
rand_imagesize_tensor.shape,rand_imagesize_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [23]:
##create tensors with zeros and ones
z =torch.zeros(size=(3,4))
print(z)
o = torch.ones(size=(3,4))
print(o)
print(o.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [26]:
##create a range of tensors
print(torch.range(2,4))##this is going to deprecated so soon
print(torch.arange(0,10))

tensor([2., 3., 4.])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


/tmp/ipykernel_12846/2983620150.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(2,4))##this is going to deprecated so soon


In [29]:
#we do some stuffs using range in tensor 
abi = torch.arange(start=5 ,end=1000,step=20)#it means it will start at 5 and end at 1000 but it willl not print all the valuues present between that instead it will add step value with it and gives the op
abi

tensor([  5,  25,  45,  65,  85, 105, 125, 145, 165, 185, 205, 225, 245, 265,
        285, 305, 325, 345, 365, 385, 405, 425, 445, 465, 485, 505, 525, 545,
        565, 585, 605, 625, 645, 665, 685, 705, 725, 745, 765, 785, 805, 825,
        845, 865, 885, 905, 925, 945, 965, 985])

In [30]:
##creating tensors like
ten_zeros = torch.zeros_like(input=abi)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [ ]:
#manipulating tensor(tensor operations)

