In [2]:
import torch
torch.__version__

'2.7.1'

In [3]:
#scalar
scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar)

0
tensor(7)


In [4]:
#vector
vector = torch.tensor([1,4])
vector

tensor([1, 4])

In [5]:
#matrix
matrix = torch.tensor([[7,8],[4,6]])
print(matrix)
print(matrix.shape)

tensor([[7, 8],
        [4, 6]])
torch.Size([2, 2])


In [6]:
#tensor
tensor = torch.tensor([[[1,2,3],[2,5,7],[8,6,4]]])
tensor

tensor([[[1, 2, 3],
         [2, 5, 7],
         [8, 6, 4]]])

In [7]:
#random tensors
rand_tensor=torch.rand(2,3,4)
rand_tensor

tensor([[[0.3413, 0.7146, 0.3402, 0.1657],
         [0.1612, 0.4458, 0.7378, 0.7381],
         [0.5571, 0.6065, 0.1935, 0.6810]],

        [[0.6236, 0.6098, 0.2768, 0.4213],
         [0.1201, 0.6307, 0.1656, 0.1328],
         [0.1928, 0.8075, 0.3521, 0.6312]]])

In [8]:
#create a random tensor with similar shape to an image tensor
random_image = torch.rand(size=(3,224,224))
random_image.shape,random_image.ndim


(torch.Size([3, 224, 224]), 3)

In [9]:
#zeros and ones
zero = torch.zeros(3,4)
zero


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
#ones
ones= torch.ones(4,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
#creating a range of tensors and tensors-like
torch.range(0,10)

/tmp/ipykernel_4544/1985955178.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
zero_to_ten = torch.arange(1,11)
zero_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#we use start end and steps inside the range
torch.arange(start=1,end=500,step=20)

tensor([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181, 201, 221, 241, 261,
        281, 301, 321, 341, 361, 381, 401, 421, 441, 461, 481])

In [14]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
#datatypes
float = torch.tensor([0.2,0.7,0.7,1.5])
print(float)
print(float.dtype)#same as int string
print(float.device)

tensor([0.2000, 0.7000, 0.7000, 1.5000])
torch.float32
cpu


In [26]:
#Manipulating tensors(tensor operation)
data = torch.tensor([1,2,3])
print(data + 10)
torch.mul(data , 3)


tensor([11, 12, 13])


tensor([3, 6, 9])

In [27]:
#matrix multiplications
#1.element multiply 2.matrix multi
#first one
print(data * data) 


tensor([1, 4, 9])


In [28]:
#second one
torch.matmul(data,data)

tensor(14)

In [36]:
#common errors in ml&dl is shape error
#example
# print(torch.matmul(torch.rand(3,2),torch.rand(3,2))) this line will show error
torch.matmul(torch.rand(3,2),torch.rand(2,3))#we need proper inner dimension matching

tensor([[0.4127, 0.3200, 0.3120],
        [0.1607, 0.3056, 0.1149],
        [0.1795, 0.3014, 0.1298]])

In [40]:
a = torch.tensor([[1,2],
                   [3,4],
                   [5,6]
                   ])
b = torch.tensor([[7,8],
                   [9,10],
                   [11,12]
                   ])
print(a)
b

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [42]:
torch.matmul(a,b.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])