In [2]:
import torch
torch.__version__

'2.7.1+cu126'

In [3]:
#scalar
scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar)

0
tensor(7)


In [4]:
#vector
vector = torch.tensor([1,4])
vector

tensor([1, 4])

In [5]:
#matrix
matrix = torch.tensor([[7,8],[4,6]])
print(matrix)
print(matrix.shape)

tensor([[7, 8],
        [4, 6]])
torch.Size([2, 2])


In [6]:
#tensor
tensor = torch.tensor([[[1,2,3],[2,5,7],[8,6,4]]])
tensor

tensor([[[1, 2, 3],
         [2, 5, 7],
         [8, 6, 4]]])

In [27]:
#random tensors
rand_tensor=torch.rand(2,3,4)
rand_tensor

tensor([[[0.8976, 0.4660, 0.0425, 0.0232],
         [0.7596, 0.9423, 0.7427, 0.4914],
         [0.2621, 0.2893, 0.2937, 0.4606]],

        [[0.4918, 0.8099, 0.5084, 0.6647],
         [0.4690, 0.7818, 0.8177, 0.5415],
         [0.2653, 0.6693, 0.5358, 0.0078]]])

In [8]:
#create a random tensor with similar shape to an image tensor
random_image = torch.rand(size=(3,224,224))
random_image.shape,random_image.ndim


(torch.Size([3, 224, 224]), 3)

In [9]:
#zeros and ones
zero = torch.zeros(3,4)
zero


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
#ones
ones= torch.ones(4,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
#creating a range of tensors and tensors-like
torch.range(0,10)

/tmp/ipykernel_15839/1985955178.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
zero_to_ten = torch.arange(1,11)
zero_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#we use start end and steps inside the range
torch.arange(start=1,end=500,step=20)

tensor([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181, 201, 221, 241, 261,
        281, 301, 321, 341, 361, 381, 401, 421, 441, 461, 481])

In [14]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
#datatypes
float = torch.tensor([0.2,0.7,0.7,1.5])
print(float)
print(float.dtype)#same as int string
print(float.device)

tensor([0.2000, 0.7000, 0.7000, 1.5000])
torch.float32
cpu


In [16]:
#Manipulating tensors(tensor operation)
data = torch.tensor([1,2,3])
print(data + 10)
torch.mul(data , 3)


tensor([11, 12, 13])


tensor([3, 6, 9])

In [17]:
#matrix multiplications
#1.element multiply 2.matrix multi
#first one
print(data * data) 


tensor([1, 4, 9])


In [18]:
#second one
torch.matmul(data,data)

tensor(14)

In [19]:
#common errors in ml&dl is shape error
#example
# print(torch.matmul(torch.rand(3,2),torch.rand(3,2))) this line will show error
torch.matmul(torch.rand(3,2),torch.rand(2,3))#we need proper inner dimension matching

tensor([[0.5686, 0.3408, 0.7957],
        [0.3784, 0.2169, 0.6559],
        [0.5661, 0.3519, 0.6329]])

In [20]:
a = torch.tensor([[1,2],
                   [3,4],
                   [5,6]
                   ])
b = torch.tensor([[7,8],
                   [9,10],
                   [11,12]
                   ])
print(a)
b

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [21]:
torch.matmul(a,b.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [22]:
#finding min,max,mean,sum
val = torch.arange(0,100,10)
val
print(torch.min(val))
print(torch.max(val))
print(torch.sum(val))

tensor(0)
tensor(90)
tensor(450)


In [23]:
#working with mean has some problem
torch.mean(val)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#the error rises because for finding the mean we need a float datatype
torch.mean(val.type(torch.float32))#we have converted the dtype to float

tensor(45.)

In [ ]:
#finding the positional positional min and max
print(val.argmin())

print(val.argmax())

tensor(0)
tensor(9)


In [ ]:
#reshaping,viewing and stacking tensors
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
reshaped = x.reshape(1,9)
print(reshaped)
reshaped1 = x.reshape(9,1)
print(reshaped1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [ ]:
#change the view if we change the values of view then x also changes
view_x = x.view(1,9)
view_x[:,0] = 11
print(view_x,x)
print(view_x.ndim)
print(view_x.shape)

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]) tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
2
torch.Size([1, 9])


In [ ]:
#stack tensors
stack = torch.stack([x,x])#we also use dim
print(stack)


tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
2
torch.Size([2, 9])


In [ ]:
#squeez and unsqueez tensors
view_x.squeeze(),view_x.shape#remove single dimension


(tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]), torch.Size([1, 9]))

In [ ]:
#unsqueez
view_x.unsqueeze(dim=1)

tensor([[[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]])

In [ ]:
#selecting data from tensors
d1 = torch.arange(1,10).reshape(1,3,3)
d1,d1.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#now lets index on our new tensor
print(d1[0][1][1])
print(d1[0][2][1])
print(d1[:,:,2])

tensor(5)
tensor(8)
tensor([[3, 6, 9]])


In [ ]:
#tensor and numpy
import numpy as np
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#some  changes in numpy
array = array + 1
array,tensor#no change in other

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#some changes in tensor
tensor=tensor+3
tensor,array#no change in other

(tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8.]))